[project]
name = "ros2-gzsim-rl-bipedal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.3.0",
    "opencv-python-headless>=5.0.0",
    "stable-baselines3[extra]>=2.9.0",
]

[tool.uv]
override-dependencies = ["opencv-python-headless>=5.0.0"]
